config:
  volume:
    name: null
    mountPath: null
    secretName: null
  serviceAccount: null
  replicas: 1
  clubName: nonamed
  serviceName: kht
  imageTag: prod-6120fa2a31323acb10d551edf3f12a83bff97f0e
  containerPort: 8089
  environment: prod
  type: be
  domain: kht.xquare.app
  prefix: null
  language: java
  private_service: "false"
  critical_service: "false"
