config:
  volume:
    name: null
    mountPath: null
    secretName: null
  serviceAccount: null
  replicas: 1
  clubName: entry
  serviceName: entry-lts
  imageTag: stag-47f97a588e2769b1d805bc7585894172ddfb78ab
  containerPort: 3002
  environment: stag
  type: fe
  domain: stag.entrydsm.hs.kr
  prefix: null
  private_service: "false"
  critical_service: "false"
