config:
  volume:
    name: null
    mountPath: null
    secretName: null
  serviceAccount: null
  replicas: 1
  clubName: entry
  serviceName: entry-lts
  imageTag: stag-bb1904b77a68a1364a6589f834645aa0cd948b26
  containerPort: 3002
  environment: stag
  type: fe
  domain: stag.entrydsm.hs.kr
  prefix: null
  private_service: "false"
  critical_service: "false"
