config:
  volume:
    name: null
    mountPath: null
    secretName: null
  serviceAccount: null
  replicas: 1
  clubName: repo
  serviceName: whopper
  imageTag: prod-b6c9b5856e63f964d79461a539789726581fd71c
  containerPort: 8080
  environment: prod
  type: be
  critical_service: "false"
  private_service: "false"
  domain: null
  prefix: /whopper
  language: java
