config:
  volume:
    name: null
    mountPath: null
    secretName: null
  serviceAccount: null
  replicas: 1
  clubName: repo
  serviceName: whopper
  imageTag: prod-7c7863d9d1d215023cddee876504215e9d142357
  containerPort: 8080
  environment: prod
  type: be
  critical_service: "false"
  private_service: "false"
  domain: null
  prefix: /whopper
  language: java
