config:
  volume:
    name: null
    mountPath: null
    secretName: null
  serviceAccount: null
  replicas: 1
  clubName: pick
  serviceName: pick-core
  imageTag: stag-30576e584db909f0bbd9fb84c7af9112cbe7cb2b
  containerPort: 8080
  environment: stag
  type: be
  domain: null
  prefix: /dsm-pick
  language: java
  private_service: "false"
  critical_service: "false"
