config:
  volume:
    name: null
    mountPath: null
    secretName: null
  serviceAccount: null
  replicas: 1
  clubName: entry
  serviceName: entry-lts
  imageTag: prod-d994a82edb609ea25909c82b0e0e4de416c684e6
  containerPort: 3002
  environment: prod
  type: fe
  domain: www.entrydsm.hs.kr
  prefix: null
  private_service: "false"
  critical_service: "false"
