config:
  volume:
    name: null
    mountPath: null
    secretName: null
  serviceAccount: null
  replicas: 1
  clubName: dms
  serviceName: dms
  imageTag: stag-337cab0feb252c9d91a430a1da7fe7d18667bec9
  containerPort: 8080
  environment: stag
  type: be
  domain: dev-api.dms-dsm.com
  prefix: null
  language: java
  private_service: "false"
  critical_service: "false"
