config:
  volume:
    name: null
    mountPath: null
    secretName: null
  serviceAccount: null
  replicas: 1
  clubName: pick
  serviceName: pick-admin
  imageTag: stag-ccafe044cee6f005bc627e8e46b0b848f50ee893
  containerPort: 3000
  environment: stag
  type: fe
  domain: pick-admin-stag.xquare.app
  prefix: null
  private_service: "false"
  critical_service: "false"
  language: nodejs
