config:
  volume:
    name: null
    mountPath: null
    secretName: null
  serviceAccount: null
  replicas: 1
  clubName: pick
  serviceName: pick-core
  imageTag: prod-b39223364145e0add43a269e63ef50c50b89bd1c
  containerPort: 8080
  environment: prod
  type: be
  domain: null
  prefix: /dsm-pick
  language: java
  private_service: "false"
  critical_service: "false"
